#! /bin/bash
# A fuzzy `git checkout`.

arg=$1

if [ "$arg" == "-" ]; then
  git checkout @{-1}
else
  match=`git rev-parse --abbrev-ref --branches="*$1*"`
  case `wc -w <<< "$match" | tr -d ' '` in
    "0") echo "error: '$arg' did not match any branch." 2>&1 ;;
    "1") git checkout $match ;;
    *) echo -e "error: '$arg' is ambigious among:\n$match" 2>&1
  esac
fi
