#! /bin/sh
# A `git grep` wrapper inspired by http://bit.ly/1cGXIch.

dir="$1"
pattern="$2"

if [ -z "$pattern" ]; then
  pattern="$dir"
  dir="."
fi

git grep -n "$pattern" -- $dir \
  | nl -s ' ' \
  | sed 's/^ *//g' \
  | sed  -E "s/^([[:digit:]]+) ([^:]+:[[:digit:]]+)(.+)/$(tput setaf 3)\1 $(tput setaf 2)\2$(tput sgr0)\3/"
