#!/usr/bin/env python
#
# Generate a random n-character string.

import random
import string
import sys

if __name__ == "__main__":
  print ''.join(random.SystemRandom().choice(string.ascii_lowercase + string.digits) for _ in range(int(sys.argv[1])))
